fix: added missing iOS appAccountToken on ProductPurchase TS interface
dooboolab-community/react-native-iap pull request #2506
Opened 2023-08-02 12:38 UTC by quentinnippert

Fixing issue #2434

2023-08-06 11:35 UTC, hyochan requested changes
Could you kindly check the CI failing?

2023-08-06 12:58 UTC, quentinnippert commented
> Could you kindly check the CI failing?

@hyochan It failed on the "**Verify no files have changed after auto-fix**" script. I think this is normal behavior since I added a property to the `transactionSk2ToPurchaseMap` method parameter and to the `ProductPurchase` interface. Am I right?

2023-08-13 18:06 UTC, hyochan approved these changes

2023-08-13 18:09 UTC, hyochan approved these changes
I think you are right! I just removed the auto-fix step in CI for the next changes.

Thanks for your contribution!

2023-08-13 18:10 UTC, merged